pipeline:
  build:
    image: node:alpine
      commands:
        - npm install
        - npm run test
        - npm run build
  deploy:
    image: node:alpine
      commands:
        - npm install
	- npm start